FROM node:boron as builder
RUN mkdir -p /usr/src/revolve
WORKDIR /usr/src/revolve
COPY package.json /usr/src/revolve
RUN npm install
COPY . /usr/src/revolve
RUN npm run build
FROM nginx
RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/src/revolve/build /usr/share/nginx/html

EXPOSE 80

RUN chown nginx.nginx /usr/share/nginx/html/ -R