services:
  - docker
  
  script:
  - docker-compose -f docker-compose-test.yml up --abort-on-container-exit
  
  before_deploy:
  # install the aws cli
  - pip install --user awscli
  # install the elastic beanstalk cli
  - pip install --user awsebcli
  # Append exe location to our PATH
  - export PATH=$PATH:$HOME/.local/bin
  
  deploy:
    provider: script
    on: 
      branch: master
    skip_cleanup: true
    script: sh $TRAVIS_BUILD_DIR/scripts/deploy.sh